name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'  # Match your local JDK version

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests and generate reports
        run: mvn test surefire-report:report

      - name: Upload test report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-report
          path: target/site/surefire-report.html
