name: PDF Report from HTML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and run tests
      run: mvn clean test site

    - name: Install PDF conversion tool
      run: sudo apt install -y wkhtmltopdf

    - name: Convert report to PDF
      run: wkhtmltopdf target/site/surefire-report.html target/surefire-report.pdf

    - name: Upload PDF report
      uses: actions/upload-artifact@v4
      with:
        name: surefire-report-pdf
        path: target/surefire-report.pdf
